export const ROLES = {
  CLIENT: 'CLIENT',
  FREELANCER: 'FREELANCER',
  ARBITRATOR: 'ARBITRATOR',
  ADMIN: 'ADMIN',
};

export const PROJECT_STATUS = {
  DRAFT: 'DRAFT',
  PENDING_FREELANCER: 'PENDING_FREELANCER',
  ACTIVE: 'ACTIVE',
  IN_DISPUTE: 'IN_DISPUTE',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
};

export const DOCUMENT_STATUS = {
  DRAFT: 'DRAFT',
  PENDING_APPROVAL: 'PENDING_APPROVAL',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  SUPERSEDED: 'SUPERSEDED',
};

export const APPROVAL_DECISION = {
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
};

export const MILESTONE_STATUS = {
  DRAFT: 'DRAFT',
  FUNDED: 'FUNDED',
  IN_PROGRESS: 'IN_PROGRESS',
  SUBMITTED: 'SUBMITTED',
  REVISION_REQUESTED: 'REVISION_REQUESTED',
  APPROVED: 'APPROVED',
  DISPUTED: 'DISPUTED',
  REFUNDED: 'REFUNDED',
};

export const CHANGE_REQUEST_STATUS = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
};

export const MESSAGE_TYPE = {
  TEXT: 'TEXT',
  FILE: 'FILE',
  CHANGE_REQUEST: 'CHANGE_REQUEST',
  SYSTEM: 'SYSTEM',
};

export const DISPUTE_STATUS = {
  COLLECTING_CLAIM: 'COLLECTING_CLAIM',
  WAITING_FOR_EVIDENCE: 'WAITING_FOR_EVIDENCE',
  WAITING_FOR_OTHER_PARTY: 'WAITING_FOR_OTHER_PARTY',
  ANALYZING: 'ANALYZING',
  RECOMMENDATION_READY: 'RECOMMENDATION_READY',
  UNDER_HUMAN_REVIEW: 'UNDER_HUMAN_REVIEW',
  RESOLVED: 'RESOLVED',
  CLOSED: 'CLOSED',
};

export const DISPUTE_CATEGORY = {
  INCOMPLETE_WORK: 'INCOMPLETE_WORK',
  LATE_DELIVERY: 'LATE_DELIVERY',
  PAYMENT_NOT_RELEASED: 'PAYMENT_NOT_RELEASED',
  REQUIREMENT_CHANGED: 'REQUIREMENT_CHANGED',
  POOR_QUALITY: 'POOR_QUALITY',
  CLIENT_GHOSTING: 'CLIENT_GHOSTING',
  FREELANCER_GHOSTING: 'FREELANCER_GHOSTING',
  PARTIAL_COMPLETION: 'PARTIAL_COMPLETION',
  OTHER: 'OTHER',
};

export const DISPUTE_SENDER_TYPE = {
  CLIENT: 'CLIENT',
  FREELANCER: 'FREELANCER',
  AI: 'AI',
  ARBITRATOR: 'ARBITRATOR',
  SYSTEM: 'SYSTEM',
};

export const EVIDENCE_AUTHENTICITY = {
  UNVERIFIED: 'UNVERIFIED',
  ACKNOWLEDGED_BY_BOTH: 'ACKNOWLEDGED_BY_BOTH',
  DISPUTED: 'DISPUTED',
  VERIFIED: 'VERIFIED',
};

export const AI_DECISIONS = {
  FULL_PAYMENT: 'FULL_PAYMENT',
  FULL_REFUND: 'FULL_REFUND',
  PARTIAL_PAYMENT: 'PARTIAL_PAYMENT',
  REVISION_REQUIRED: 'REVISION_REQUIRED',
  DEADLINE_EXTENSION: 'DEADLINE_EXTENSION',
  INSUFFICIENT_EVIDENCE: 'INSUFFICIENT_EVIDENCE',
};

export const DEFAULT_RESPONSE_DEADLINE_DAYS = 3;
